goldmark:
  extensions:
    definitionList: true
    footnote: true
    linkify: true
    strikethrough: true
    table: true
    taskList: true
    typographer: true
  parser:
    attribute:
      block: false
      title: true
    autoHeadingID: true
    autoHeadingIDType: github
  renderer:
    hardWraps: false
    unsafe: true
    xhtml: false