issoHost: "http://localhost:1314"
env: develop # to enable google analytics, opengraph, twitter-cards and schema.

title: LH-Home
description: "清净的小屋"
keywords: [博客, 技术, Python, 生物信息学]
# author: [Lu]
images: []
DateFormat: "2006-01-02"
defaultTheme: light # dark, light
disableThemeToggle: false
ShowReadingTime: true
ShowShareButtons: false
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
disableSpecial1stPost: false
disableScrollToTop: false
comments: true
hidemeta: false
hideSummary: false
showtoc: true
tocopen: false

assets:
  # disableHLJS: true # to disable highlight.js
  # disableFingerprinting: true
  favicon: "/logos/favicon.png"
  favicon16x16: "/logos/favicon-small.png"
  favicon32x32: "/logos/favicon-mini.png"
  apple_touch_icon: "/logos/favicon.png"
  safari_pinned_tab: "/logos/favicon.png"

label:
  text: "主页"
  icon: /logos/foxTail_reverse.png
  darkicon: /logos/foxTail.png
  iconHeight: 30

# home-info mode
homeInfoParams:
  Title: "LH-Home"
  Content: "满地都是六便士，只要抬头就能看见月亮。"

socialIcons:
  - name: github
    url: "https://github.com/zinklu"
    description: 炉子的GitHub
  - name: zhihu
    url: "https://www.zhihu.com/people/ming-zi-shi-xiao-ming"

cover:
  hidden: true # hide everywhere but not in structured data
  hiddenInList: true # hide on list pages and home
  hiddenInSingle: true # hide on single page

# for search
# https://fusejs.io/api/options.html
fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]
