before_script:
  - echo "add ssh key"
  - mkdir -p ~/.ssh
  - echo "$ID_RSA" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod -R 600 ~/.ssh/id_rsa

  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  
  - echo "add ssh done"

stages: # List of stages for jobs, and their order of execution
  # - build
  - before_script
  - deploy

build-job: # This job runs in the build stage, which runs first.
  stage: deploy
  script:
    - echo "current branch is $CI_COMMIT_BRANCH, building..."
    - echo "building static file..."
    - hugo
    - echo "build complete."
    - echo "rsync to remote ...."
    - echo "remote server is  $REMOTE_SERVER, remote path is $REMOTE_SERVER_PATH"
    - echo "running rsync -aP --rsh=ssh public/ $REMOTE_SERVER:$REMOTE_SERVER_PATH"
    - rsync -aP --rsh=ssh public/ $REMOTE_SERVER:$REMOTE_SERVER_PATH
    - echo "rsync complete."
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
